#!/bin/bash

PYTHON_VERSION=$(echo $DOCKER_TAG | cut -d "-" -f2)

if [ $DOCKER_TAG == "latest" ]
then
  docker build . --build-arg PYTHON_VERSION=${DOCKER_TAG} -t ${IMAGE_NAME}
else
  docker build . --build-arg PYTHON_VERSION=${PYTHON_VERSION} -t ${IMAGE_NAME}
fi